### ISSUE TITLE
watch history, shortcuts, buffering

### ISSUE THREAD

**Issue by ISFU** [goodtube4u/goodtube#23]
I'm having issues with videos being recommended to me again that I didn't see in my watch history.
Also, the shortcuts I was using were no longer working,
and there was a lot of buffering when watching videos.

**Comment by goodtube4u** [comment]
Hello. I am not completely sure what you are asked here exactly, but to help explain:

- This does not change how your watch history works, or change your recommended videos. If you are seeing strange recommendations, that must be coming from Youtube.
- All keyboard shortcuts should work. Which shortcuts are not working?
- These videos are not loaded directly from the Youtube servers, so you will find that they load slower sometimes. It might help you to change the "Video source". There is a button for this at the bottom of the player. Find one that works best for you.

Hopefully that helps! Closing this issue for now, re-open it if you need any more assistance :)

**Comment by ISFU** [comment]
Hello.  First of all, thank you for creating this script.

Perhaps I wasn't clear enough. After turning on this script and watching a specific video, I went to YouTube Home and the same video was recommended. And when I went to my watch history, it was supposed to be at the top of my watch list, but it wasn't.

For example, the full-screen shortcut 'F' didn't work, and after some testing, the 'command F' works. And I've been using the '<' or '>' buttons to change the playback speed, but that doesn't work either.

Thanks again.

**Comment by goodtube4u** [comment]
Ah that is much more clear, thanks.

Watch history -
- Often the watch histroy takes a few minutes to update (not sure why, but this seems to simply be how Youtube works). It's likely that the video you watched will show up there soon. If you look again, is it there now?
- In the background, the normal hidden Youtube player will often play an ad at the start of the video. I think if you don't watch the video long enough for the ad to finish, it won't be added to your watch history. I say "I think" because I'm not completely sure about that.

Keyboard shortcuts:
'f' for fullscreen should be working (and works correctly for me).

It looks like you are correct that the '<' and '>' playback speed shortcuts are not working. I will fix these today and put it in the next update! :)

Here are the other supported shortcuts:
't' = Theater mode
'i' = Miniplayer / picture in picture
'home' = Start of the video
'end' = End of the video
'shift + n' = Next video
'shift + p' = Previous video (only works in playlists)
0, 1, 2, 3, 4, 5, 6, 7, 8, 9 = Skip to 0%, 10%, 20%, 30%, etc
'left' / 'right' = Skip backward / forward 5 seconds
'j' / 'l' = Skip backward / forward 10 seconds
'spacebar' = Play / pause
'm' = Mute
'up' / 'down' = Volume up / down
'/' = Go to search box

**Comment by goodtube4u** [comment]
I have just fixed the '>' and '<' playback speed shortcuts. Please update the code (you will see a popup for this on Youtube).

Enjoy! :)

**Comment by ISFU** [comment]
All issues were resolved except for a little slow loading when playing videos. I'm more than satisfied, thank you!

**Comment by goodtube4u** [comment]
You're very welcome my friend.
