### ISSUE TITLE
Music playlist issues

### ISSUE THREAD

**Issue by Dodsy-91** [goodtube4u/goodtube#3]
Trying to play music videos through playlists is impossible, they play for maybe 3 to 5 seconds then skip to the next and so on.

**Comment by goodtube4u** [comment]
Ah yep, seen this issue before. The problem is that you've still got your regular adblocker enabled for Youtube. You can usually turn it off for one site only (eg, youtube). Give that a try, should work for ya.

Basically it's detecting your other adblocker, and skipping the videos.

**Comment by Dodsy-91** [comment]
I have disabled a blocker. I have updated the script to the last update, but it still won't work with playlists.

**Comment by Dodsy-91** [comment]
I have tried that, but after managing to play one video, it then just skips though the rest of the playlist.

**Comment by goodtube4u** [comment]
Very weird. I'm pretty sure this is an issue with your other adblockers or browser extensions.

Try disabling GoodTube for a sec and then check out normal Youtube. If you're seeing the "adblockers are not allowed" message - then some other plugin / adblocker you're running is the cause of the issue. It shows that message for a few seconds, then skips to the next video in the playlist.

Once you've confirmed that, with GoodTube off, Youtube is behaving normally - then turn it back on and everything should work. Let me know how you go :)

**Comment by Dodsy-91** [comment]
So, I have disabled GoodTube and ad blocker and when playing a video on YouTube adverts are on which is as I would expect.

As soon as I enable GoodTube again with ad blocker (uBlock Origin) disabled, it starts skipping through every video in a playlist.

**Comment by goodtube4u** [comment]
Damn that sucks. Can you provide some more info so I can debug? If I can make the same thing happen on my end then I will have more luck solving it for ya.

What browser are you using?
What userscript extension are you using (Tampermonkey, Violentmonkey, etc?)
What device are you using? (Windows, mac, android, iOS)

Alternatively, can you try Chrome + Tampermonkey? Can confirm that setup works fine on desktop / windows.

Cheers,
Jamen

**Comment by Dodsy-91** [comment]
> Damn that sucks. Can you provide some more info so I can debug? If I can make the same thing happen on my end then I will have more luck solving it for ya.
> 
> What browser are you using? What userscript extension are you using (Tampermonkey, Violentmonkey, etc?) What device are you using? (Windows, mac, android, iOS)
> 
> Alternatively, can you try Chrome + Tampermonkey? Can confirm that setup works fine on desktop / windows.
> 
> Cheers, Jamen

Firefox latest beta version 
Tampermonkey
And it's on windows 11 - 64 bit

**Comment by goodtube4u** [comment]
So I downloaded Firefox Beta, added Tampermonkey + GoodTube.

All seems to be working on my end, played multiple tracks without issue from this playlist:
![image](https://github.com/goodtube4u/goodtube/assets/167619147/d0a16fdf-f86e-452c-ab3e-fe24b6fbd504)

Sorry I know that's not particularly helpful. I really do think it's an issue with another extension.

If you're willing to do so;
- Try disabling all your other browser extensions, except Tampermonkey. Try that. If it works something else is messing with stuff.
- You could also try deleting your cookies and browsing history. I know that's really painful to do, but sometimes Youtube looks at this.

Honestly though, likely another extension - rather than history or cookies.

If you still can't get it working, try another browser? Maybe normal Firefox, or Chrome?

Good luck!
